# ==============================================================================
# File        : tasks/install.yml
# Description : Package installation tasks for Restic
# Author      : SudoShea
# Version     : 1.0.2
# License     : MIT
# ==============================================================================
---
- name: Install Restic backup package
  ansible.builtin.package:
    name: restic
    state: present
