# ==============================================================================
# GitHub Action : .github/workflows/lint.yml
# Description   : Runs ansible-lint to enforce syntax and best practices
# Author        : SudoShea
# Version       : 1.0.5
# License       : MIT
# ==============================================================================
name: Ansible Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
